
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
updates:
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: daily
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
