name: "Build and publish common libs"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
      - name: Enable Corepack
        run: corepack enable
      - name: "install dependencies"
        run: "yarn --immutable"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.READER_TOKEN }}"
      - name: "test packages"
        run: "yarn workspaces foreach --all --exclude . run test"
      - name: "build storybook"
        run: "yarn run build-storybook"
      - name: "build packages"
        run: "yarn workspaces foreach --all run build"
      - name: "Deploy storybook"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder the action should deploy.
      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset release
          createGithubReleases: false
        env:
          #NPM_TOKEN: ${{ secrets.NPM_AUTOMATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION }}
#      - name: "Login"
#        run: |
#          git config user.email "aap-innbygger@nav.no"
#          git config user.name "Team Innbygger"
#          git remote set-url origin https://github-actions[bot]:$GITHUB_TOKEN@github.com/navikt/aap-felles-innbygger.git
#          git fetch origin
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#      - name: "Create a .npmrc file for the github package repository"
#        uses: "FerLuisxd/create-npmrc@3"
#        with:
#          org_name: "navikt"
#        env:
#          AUTH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
#      - name: "Push"
#        run: |
#          npm run version:patch
#          npm run publish:ci
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
