name: "Build and deploy aap-soknad-next"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: "install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.READER_TOKEN }}"
      - name: "build packages"
        run: "npm run build"
      - name: "build storybook"
        run: "npm run build-storybook"
      - name: "build packages"
        run: "npm run build"
      - name: "Deploy storybook"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder the action should deploy.
      - name: "Login"
        run: |
          git config user.email "aap-innbygger@nav.no"
          git config user.name "Team Innbygger"
          git remote set-url origin https://github-actions[bot]:$GITHUB_TOKEN@github.com/navikt/aap-felles-innbygger.git
          git fetch origin
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Create a .npmrc file for the github package repository"
        uses: "FerLuisxd/create-npmrc@3"
        with:
          org_name: "navikt"
        env:
          AUTH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      - name: "Push"
        run: "npm run publish:ci"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"