name: "Build and publish common libs"
on:
  pull_request:

env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"

jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      SKIP_YARN_COREPACK_CHECK: true
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: "actions/checkout@v7"
      - uses: "actions/setup-node@v7"
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
      - name: Enable Corepack
        run: corepack enable
      - name: "Update lockfile for Dependabot"
        if: github.actor == 'dependabot[bot]'
        run: |
          yarn install
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yarn.lock
          git diff --staged --quiet || git commit -m "chore: update yarn.lock"
          git push origin HEAD:${{ github.head_ref }}
      - name: "install dependencies"
        run: "yarn --immutable"
      - name: "test packages"
        run: "yarn workspaces foreach --all --exclude . run test"
      - name: "build packages"
        run: "yarn workspaces foreach --all --exclude . run build"
